<LoginScreen>:
    GridLayout:
        GridLayout:
            Label:
                text:"User Login"
            TextInput:
                hint_text: "Username"
            TextInput:
                hint_text: "Password"
        GridLayout:
            cols:2
            Button:
                text:"Forgot Password"
            Button:
                text:"Sign up"
<RootWidget>:
    LoginScreen:
        name:"login_screen"
